# Generated by Django 3.2 on 2021-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('salt', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
